// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUJzqgMWWyGCvtLz0tMOu1xJBh9rqOODY',
    appId: '1:305145811277:web:b3fc49bd06eb863d00e704',
    messagingSenderId: '305145811277',
    projectId: 'tailor-ddff7',
    authDomain: 'tailor-ddff7.firebaseapp.com',
    storageBucket: 'tailor-ddff7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXdlQgLpmlLfcIOxusUdTtwQU_4PA2NF8',
    appId: '1:305145811277:android:0fe9cc9e021e349700e704',
    messagingSenderId: '305145811277',
    projectId: 'tailor-ddff7',
    storageBucket: 'tailor-ddff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1E2-PIZ1OjZ7wo8HHbFRxXF2Wv6XKKEE',
    appId: '1:305145811277:ios:4402623746d18e0000e704',
    messagingSenderId: '305145811277',
    projectId: 'tailor-ddff7',
    storageBucket: 'tailor-ddff7.firebasestorage.app',
    iosBundleId: 'com.example.tailorPlatflorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1E2-PIZ1OjZ7wo8HHbFRxXF2Wv6XKKEE',
    appId: '1:305145811277:ios:4402623746d18e0000e704',
    messagingSenderId: '305145811277',
    projectId: 'tailor-ddff7',
    storageBucket: 'tailor-ddff7.firebasestorage.app',
    iosBundleId: 'com.example.tailorPlatflorm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUJzqgMWWyGCvtLz0tMOu1xJBh9rqOODY',
    appId: '1:305145811277:web:bca718e8256374d100e704',
    messagingSenderId: '305145811277',
    projectId: 'tailor-ddff7',
    authDomain: 'tailor-ddff7.firebaseapp.com',
    storageBucket: 'tailor-ddff7.firebasestorage.app',
  );
}
